const express = require('express')
const path= require('path')
const app = express()

const defaultRoutes=require(`./routes/default`);
const restaurantRoutes = require('./routes/restaurants')
app.set("views" , path.join(__dirname, "views"))
//views its folder name for html files
//path to the folder that contains your template files
app.set("view engine", "ejs");// we tell express that we wanna use special templates
app.use(express.static( "public"));
app.use(express.urlencoded({extended:false}))


app.use("/" , defaultRoutes)
app.use("/", restaurantRoutes)

// function pathWay (step){
//     return path.join(__dirname, 'data', step)
// }
app.get('/index', function(req, res){
    res.render('index')
    // res.sendFile(directPath("index.ejs"))
})





app.use(function(req, res){
    res.status(404).render("404error")
})

app.use(function(error, req, res,next){
 res.status(500).render("500error")
})

//error object generated by express and contains information about errors

app.listen(3000)




// app.get('/index', function(req, res){
//     const htmlFilePath=path.join(__dirname,"views", "index.ejs");
//     res.sendFile(htmlFilePath)
// })
//
// app.get('/', function(req, res){
//     const htmlFilePath=path.join(__dirname,"views", "index.ejs");
//     res.sendFile(htmlFilePath)
// })
//
// app.get("/restaurants", function(req, res){
//     const htmlFilePath=path.join(__dirname, "views", "restaurants.ejs")
//     res.sendFile(htmlFilePath)
// })
//
// app.get("/recommend", function(req, res){
//     const htmlFilePath=path.join(__dirname, "views", "recommend.ejs")
//     res.sendFile(htmlFilePath)
// })
//
// app.get("/confirm", function(req, res){
//     const htmlFilePath=path.join(__dirname, "views", "confirm.ejs")
//     res.sendFile(htmlFilePath)
// })
//
// app.get("/about", function(req, res){
//     const htmlFilePath=path.join(__dirname, "views", "about.ejs")
//     res.sendFile(htmlFilePath)
// })

